package com.iotplatform.utilities;

import java.util.ArrayList;
import java.util.Hashtable;
import java.util.LinkedHashMap;

/*
 * ValidationResult is used to hold validation result that will be returned to the service
 */
public class ValidationResult {

	/*
	 * htblClassURIIndividualQueryFields holds rows generated by validation for
	 * example of a row is:
	 * 
	 * http://purl.oclc.org/NET/UNIS/fiware/iot-lite#Coverage={a27c737b-626f-
	 * 40ff-9eee-be872ada5051=[QueryField [prefixedPropertyName=iot-lite:id,
	 * isValueObject=false, objectValueTypeClassName=null,
	 * individualUniqueIdentifier=null, subjectVariableName=null,
	 * isValueObjectType=false], QueryField [prefixedPropertyName=geo:location,
	 * isValueObject=true,
	 * objectValueTypeClassName=http://www.w3.org/2003/01/geo/wgs84_pos#Point,
	 * individualUniqueIdentifier=7ad7e3da-6f3d-499a-838c-357932c434b3,
	 * subjectVariableName=null, isValueObjectType=false]]}
	 */
	private LinkedHashMap<String, LinkedHashMap<String, ArrayList<QueryField>>> htblClassNameProperty;

	/*
	 * htblOptions holds options that can be given by user for queryRequest and
	 * the value is a boolean that tells whether to enable or disable options
	 */
	private Hashtable<String, Boolean> htblOptions;

	public ValidationResult(
			LinkedHashMap<String, LinkedHashMap<String, ArrayList<QueryField>>> htblClassURIIndividualQueryFields,
			Hashtable<String, Boolean> htblOptions) {
		this.htblClassNameProperty = htblClassURIIndividualQueryFields;
		this.htblOptions = htblOptions;
	}

	public LinkedHashMap<String, LinkedHashMap<String, ArrayList<QueryField>>> getHtblClassNameProperty() {
		return htblClassNameProperty;
	}

	public Hashtable<String, Boolean> getHtblOptions() {
		return htblOptions;
	}

}
